languageCode = "en"
languageName = "English"
weight = 1
title = "SlothCoder"

[params]
displayName = "English"
isoCode = "en-US"
rtl = false
logo = "img/logo.png"
description = "My personal tech blog"
copyright = "Â© 2019-{ year } SlothCoder"
dateFormat = "Jan 2, 2006"

[params.author]
name = "Sloth"
image = "img/avatar.png"
headline = "Writing code daily, writing thoughts occasionally"
bio = "Java Backend Developer | System Design | Engineering Practice"
links = [
    { link = "https://slothcoder.cn" },
    { github = "https://github.com/GuoHuaijian" },
    { email = "guohuaijian9527@gmail.com" }
]
