languageCode = "en-us"
languageName = "English"
weight = 1
title = "Guo's Notes"

[params]
displayName = "EN"
isoCode = "en-us"
rtl = false
logo = "img/logo.png"
description = "My personal website"
dateFormat = "January 2, 2006"

[params.author]
name = "Guo"
image = "img/avatar.png"
headline = "Coding • Writing • Living"
bio = "Backend developer & open-source enthusiast"
links = [
  { link = "https://guohuaijian.github.io" },
  { github = "https://github.com/GuoHuaijian" },
  { email = "guohuaijian9527@gmail.com" }
]
