languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "SlothCoder"

[params]
    displayName = "中文"
    isoCode = "zh-cn"
    rtl = false
    logo = "img/logo.png"
    description = "我的个人网站"
    copyright = "© 2019-{ year } 她是故人"
    dateFormat = "2006年1月2日"

[params.author]
    name = "云上笔记"
    image = "img/avatar.png"
    headline = "日常写 Bug、偶尔写点博客"
    bio = "Java后端开发｜全栈工程师"
    links = [
        { link = "https://guohuaijian.github.io" },
        { github = "https://github.com/GuoHuaijian" },
        { email = "guohuaijian9527@gmail.com" }
    ]
